import type { Village, CreditListing, Transaction, EnergyReading, User, AdminOverview, MonthlyData } from '@/types';

export const mockVillages: Village[] = [
  {
    id: '1',
    name: 'Alluru',
    district: 'Anantapur',
    state: 'Karnataka',
    lat: 15.3,
    lng: 77.6,
    population: 820,
    total_households: 180,
    enrolled_households: 47,
    status: 'active',
    has_water_stress: false,
    bis_baseline_liters: 135,
    target_liters: 100,
    water_credit_price: 15,
    total_solar_capacity_kw: 70.5,
    avg_panel_capacity_kw: 1.5,
    solar_credit_price: 45,
    daily_sunlight_hours: 5.5,
    total_credits_generated: 3810,
    total_credits_sold: 2400,
    total_payout: 75600,
    co2_avoided_tonnes: 180,
    monitor_name: 'Ramesh K',
    monitor_phone: '+91 98765 43210',
    created_at: '2025-08-15',
  },
  {
    id: '2',
    name: 'Devanahalli',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    lat: 13.25,
    lng: 77.71,
    population: 1200,
    total_households: 280,
    enrolled_households: 0,
    status: 'onboarding',
    has_water_stress: false,
    bis_baseline_liters: 135,
    target_liters: 100,
    water_credit_price: 15,
    total_solar_capacity_kw: 0,
    avg_panel_capacity_kw: 1.5,
    solar_credit_price: 45,
    daily_sunlight_hours: 5.2,
    total_credits_generated: 0,
    total_credits_sold: 0,
    total_payout: 0,
    co2_avoided_tonnes: 0,
    monitor_name: null,
    monitor_phone: null,
    created_at: '2026-01-10',
  },
  {
    id: '3',
    name: 'Wai',
    district: 'Satara',
    state: 'Maharashtra',
    lat: 17.95,
    lng: 73.89,
    population: 950,
    total_households: 210,
    enrolled_households: 0,
    status: 'pipeline',
    has_water_stress: true,
    bis_baseline_liters: 135,
    target_liters: 100,
    water_credit_price: 15,
    total_solar_capacity_kw: 0,
    avg_panel_capacity_kw: 1.5,
    solar_credit_price: 45,
    daily_sunlight_hours: 5.0,
    total_credits_generated: 0,
    total_credits_sold: 0,
    total_payout: 0,
    co2_avoided_tonnes: 0,
    monitor_name: null,
    monitor_phone: null,
    created_at: '2026-03-01',
  },
];

export const mockListings: CreditListing[] = [
  {
    id: '1',
    village_id: '1',
    village_name: 'Alluru',
    village_district: 'Anantapur',
    village_state: 'Karnataka',
    listing_type: 'solar',
    batch_code: 'ALLURU-SOL-2026-04',
    total_credits: 420,
    credits_remaining: 420,
    price_per_credit: 45,
    total_bundle_value: 18900,
    gps_verified: true,
    meter_certified: true,
    brsr_ready: true,
    sdg_tags: ['SDG 7', 'SDG 1', 'SDG 13'],
    status: 'available',
    month: 4,
    year: 2026,
    listed_at: '2026-04-01',
    expires_at: '2026-07-01',
    enrolled_households: 47,
    solar_capacity_kw: 70.5,
  },
  {
    id: '2',
    village_id: '1',
    village_name: 'Alluru',
    village_district: 'Anantapur',
    village_state: 'Karnataka',
    listing_type: 'solar',
    batch_code: 'ALLURU-SOL-2026-03',
    total_credits: 400,
    credits_remaining: 0,
    price_per_credit: 45,
    total_bundle_value: 18000,
    gps_verified: true,
    meter_certified: true,
    brsr_ready: true,
    sdg_tags: ['SDG 7', 'SDG 1', 'SDG 13'],
    status: 'sold_out',
    month: 3,
    year: 2026,
    listed_at: '2026-03-01',
    expires_at: '2026-06-01',
    enrolled_households: 47,
    solar_capacity_kw: 70.5,
  },
  {
    id: '3',
    village_id: '3',
    village_name: 'Wai',
    village_district: 'Satara',
    village_state: 'Maharashtra',
    listing_type: 'combined',
    batch_code: 'WAI-CMB-2026-04',
    total_credits: 1260,
    credits_remaining: 1260,
    price_per_credit: 15,
    total_bundle_value: 18900,
    gps_verified: true,
    meter_certified: false,
    brsr_ready: false,
    sdg_tags: ['SDG 6', 'SDG 7', 'SDG 13'],
    status: 'available',
    month: 4,
    year: 2026,
    listed_at: '2026-04-01',
    expires_at: '2026-07-01',
    enrolled_households: 0,
    solar_capacity_kw: 0,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    corporate_id: 'corp1',
    listing_id: '2',
    village_id: '1',
    corporate_name: 'Infosys Ltd',
    village_name: 'Alluru',
    credits_purchased: 200,
    price_per_credit: 45,
    total_amount: 9000,
    gramcredit_fee: 2700,
    village_share: 6300,
    status: 'completed',
    payment_method: 'Bank Transfer',
    invoice_id: 'GC-2026-0001',
    brsr_document_url: '#',
    purchased_at: '2026-03-15',
  },
  {
    id: '2',
    corporate_id: 'corp2',
    listing_id: '2',
    village_id: '1',
    corporate_name: 'Bosch India',
    village_name: 'Alluru',
    credits_purchased: 200,
    price_per_credit: 45,
    total_amount: 9000,
    gramcredit_fee: 2700,
    village_share: 6300,
    status: 'completed',
    payment_method: 'Bank Transfer',
    invoice_id: 'GC-2026-0002',
    brsr_document_url: '#',
    purchased_at: '2026-03-20',
  },
];

const months = ['Oct 2025', 'Nov 2025', 'Dec 2025', 'Jan 2026', 'Feb 2026', 'Mar 2026'];

export const mockMonthlyData: MonthlyData[] = months.map((month, i) => ({
  month,
  credits_generated: 580 + Math.floor(Math.random() * 100),
  credits_sold: 400 + Math.floor(Math.random() * 150),
  revenue: 15000 + Math.floor(Math.random() * 5000),
  payout: 10000 + Math.floor(Math.random() * 4000),
}));

export const mockReadings: EnergyReading[] = months.map((_, i) => ({
  id: `r${i + 1}`,
  village_id: '1',
  user_id: 'u1',
  reading_type: 'solar' as const,
  kwh_generated: 240 + Math.floor(Math.random() * 30),
  panel_capacity_kw: 1.5,
  sunlight_hours_benchmark: 5.5,
  liters_conserved: null,
  credits_calculated: 24 + Math.floor(Math.random() * 3),
  month: 10 + i > 12 ? 10 + i - 12 : 10 + i,
  year: 10 + i > 12 ? 2026 : 2025,
  verified: i < 4,
  submitted_at: `2025-${String(10 + i > 12 ? 10 + i - 12 : 10 + i).padStart(2, '0')}-28`,
  user_name: 'Priya S',
  village_name: 'Alluru',
}));

export const mockAdminOverview: AdminOverview = {
  total_villages: 3,
  active_villages: 1,
  onboarding_villages: 1,
  pipeline_villages: 1,
  total_enrolled_households: 47,
  total_credits_generated: 3810,
  total_credits_sold: 2400,
  total_revenue: 32400,
  total_paid_to_villages: 75600,
};

export const mockCurrentUser: User = {
  id: 'u1',
  name: 'Priya Sharma',
  email: 'user1@alluru.in',
  role: 'user',
  phone: '+91 99887 76655',
  created_at: '2025-08-20',
  villager_profile: {
    village_id: '1',
    village_name: 'Alluru',
    household_size: 4,
    has_panel: true,
    panel_capacity_kw: 1.5,
    panel_installed_date: '2025-09-01',
    bank_account_linked: true,
    upi_id: 'priya@upi',
    total_credits_earned: 156,
    total_payout_received: 4914,
  },
};

export const mockCorporateUser: User = {
  id: 'corp1',
  name: 'Rajesh Menon',
  email: 'infosys@corp.in',
  role: 'corporate',
  phone: '+91 98765 00001',
  created_at: '2025-10-01',
  corporate_profile: {
    company_name: 'Infosys Ltd',
    gstin: '29AABCI1234F1ZN',
    brsr_reporting: true,
    total_credits_acquired: 200,
    total_spent: 9000,
  },
};
